export const TITLE = {
  FR: [
    { text: 'Studio ', isBlue: false },
    { text: 'créatif ', isBlue: false },
    { text: 'qui ', isBlue: false },
    { text: 'concoit ', isBlue: false },
    { text: 'des ', isBlue: false },
    { text: 'sites ', isBlue: true },
    { text: 'web ', isBlue: true },
    { text: 'uniques ', isBlue: false },
    { text: 'et ', isBlue: false },
    { text: 'immersifs ', isBlue: false },
    { text: 'pour ', isBlue: false },
    { text: 'les ', isBlue: false },
    { text: 'entreprises ', isBlue: true },
    { text: 'avant-', isBlue: true },
    { text: 'gardistes.', isBlue: true },
  ],
  EN: [
    { text: 'Creative ', isBlue: false },
    { text: 'studio ', isBlue: false },
    { text: 'crafting ', isBlue: false },
    { text: 'unique ', isBlue: true },
    { text: 'and ', isBlue: true },
    { text: 'immersive ', isBlue: true },
    { text: 'websites ', isBlue: false },
    { text: 'for ', isBlue: false },
    { text: 'forward-', isBlue: true },
    { text: 'thinking ', isBlue: true },
    { text: 'companies.', isBlue: true },
  ],
};
